# Database Configuration
DB_URL=jdbc:mysql://localhost:3306/mobile_banking?useSSL=false&serverTimezone=UTC
DB_USER=root
DB_PASS=P@ssw0rd

# JWT properties
JWT_SECRET=s5hU2WKnL0up2QeQUf/HzqLGICBMfwUApFI/SYj0keo=
#30min
JWT_EXPIRATION=1800000
